[package]
name = "rocketmq"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
hex = "0.4"
rand = "0.7"
tokio = { version = "0.2", features = ["tcp", "dns", "io-util", "macros"] }
num_enum = "0.5.0"
reqwest = { version = "0.10.6", default-features = false, features = ["blocking"] }
futures = "0.3.5"
tokio-util = "0.3.1"
bytes = "0.5.5"
